fix: issue 1823 improves tracer OTLP docs
redpanda-data/connect pull request #1834
Opened 2023-04-04 17:43 UTC by cezar-tech

2023-04-04 17:45 UTC, cezar-tech commented on internal/impl/otlp/tracer_otlp.go
> +var cliVersion = cli.Version
Could this cause any bugs during the build/ testing ?
can I reference this variable this way ?

2023-05-10 08:50 UTC, Jeffail commented
One issue here, which I think is maybe why the behaviour is as it currently is right now, is that the field docs will now be bound to the version and date stamps, which are dynamically set at build time. We can't really get away with that as it'll break docs generation that precedes a release. It'd also be kind of annoying that the field spec will change for every new tag.

I think rather than making the defaults explicit via a default flag we should just explain the behaviour within the field description.

2023-05-16 12:25 UTC, cezar-tech commented
@Jeffail I didn't understand this phrase:
> is that the field docs will now be bound to the version and date stamps,

What line specifically do you refer to ?

I have changed more than the necessary to apply this fix actually, I could rollback some lines and change specifically the description like you said.

My issue was only this part that didn't talk about the defaults:
![image](https://github.com/benthosdev/benthos/assets/56096912/614fb8f5-f236-4fa2-bb36-b70ada6daeb8)

2023-05-28 09:15 UTC, Jeffail commented
> What line specifically do you refer to ?

What I mean is that the line `string(svcVerKey):  cliVersion,` will change constantly as it's set dynamically at build time, and when changes to docs occur it causes build errors as they're assumed stale. Rather than set an explicit (and dynamic) default value for the field docs I'd be happier to expand the description to state "A map of tags to add to all tracing spans. The tags `" + string(svcNameKey) + "` and `" + string(svcVerKey) + " are added automatically when omitted."

2024-02-17 00:39 UTC, lucasoares commented
> > What line specifically do you refer to ?
> 
> What I mean is that the line `string(svcVerKey): cliVersion,` will change constantly as it's set dynamically at build time, and when changes to docs occur it causes build errors as they're assumed stale. Rather than set an explicit (and dynamic) default value for the field docs I'd be happier to expand the description to state:
> 
> ```
> "A map of tags to add to all tracing spans. The tags `" + string(svcNameKey) + "` and `" + string(svcVerKey) + " are added automatically when omitted."
> ```

What if we set the version as something like `<benthos binary version>` just to be clear in the documentation? @cezar-tech

2024-02-17 00:47 UTC, lucasoares requested changes
I have one problem with the current implementation. If we let things like this, we will not be able to change the service name and version by using OpenTelemetry's environment variables since the component configuration will always be set. We should only set the fixed name and version if the resource can't be built by the environment itself

`OTEL_RESOURCE_ATTRIBUTES` - https://opentelemetry.io/docs/specs/otel/resource/sdk/#specifying-resource-information-via-an-environment-variable

`OTEL_SERVICE_NAME` - https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#general-sdk-configuration

Code example to check if the user has set these attributes:

```
// Check if the user has already set a service name and versrion tag by using environment variables
resourceData := resource.Environment().Iter()

for resourceData.Next() {
kv := resourceData.Attribute()

if kv.Key == semconv.ServiceNameKey {
	// do not set the service name
}

if kv.Key == semconv.ServiceVersionKey {
	// do not set the service version
}
}
```

2025-01-27 14:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/connect?pullRequest=1834) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/connect?pullRequest=1834) before we can accept your contribution.<br/><hr/>**Cezar** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/connect?pullRequest=1834) it.</sub>

2025-01-27 14:50 UTC, cezar-tech commented
Hi guys shall we get back into this ? I would like to help

2025-01-27 17:14 UTC, closed without merging